<?php
// Include TCPDF library (you need to point to your library's path)
require_once('vendor/tcpdf.php');

// Database connection
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "db_students";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Fetch data from students table
$sql = "SELECT ID, En_name, Kh_name, Gender FROM tb_student";
$result = $conn->query($sql);

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('School Management System');
$pdf->SetTitle('Student Report');
$pdf->SetSubject('Report');
$pdf->SetKeywords('TCPDF, PDF, report, student');

// Set default header and footer
$pdf->setPrintHeader(true);
$pdf->setPrintFooter(true);

// Set header and footer data
$pdf->SetHeaderData('', 0, 'Student Report', 'Generated by PHP with TCPDF');

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add title
$pdf->Cell(0, 10, 'Student Report', 0, 1, 'C');

// Start building the table HTML
$html = '
<table border="1" cellpadding="5">
    <thead>
        <tr>
            <th><b>ID</b></th>
            <th><b>Name</b></th>
            <th><b>Name</b></th>
            <th><b>Gender</b></th>
        </tr>
    </thead>
    <tbody>';

// Loop through the database results and add them to the table
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $html .= '
        <tr>
            <td>' . $row['ID'] . '</td>
            <td>' . $row['En_name'] . '</td>
            <td>' . $row['Kh_name'] . '</td>
            <td>' . $row['Gender'] . '</td>
        </tr>';
    }
} else {
    $html .= '<tr><td colspan="3">No records found</td></tr>';
}

$html .= '
    </tbody>
</table>';

// Output the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output the PDF
$pdf->Output('student_report.pdf', 'I');

// Close the database connection
$conn->close();